module.exports = [
    {
        name: "Couch", 
        price: 100, 
        image: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.home-dzine.co.za%2F2016%2Fjan%2F189.jpg&f=1&nofb=1", 
        description: "This is a great couch.", 
        category: "Furniture",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "TV Stand", 
        price: 75, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.ZPVnC2W9OXTPZtEpv8yrbgAAAA%26pid%3DApi&f=1", 
        description: "As good as new tv is not including", 
        category: "Furniture",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "X-MEN Acrade Game", 
        price: 1700, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F1.bp.blogspot.com%2F_j47CXrjYTRg%2FTR6vI599jfI%2FAAAAAAAAAIg%2FWRY5SGQ8GPM%2Fs1600%2Fxmenarcade.jpg&f=1&nofb=1", 
        description: "Fully Operational and Awesome", 
        catergory: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "HD Projector", 
        price: 699, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIVmJD50Ao_aPXb_Dpvg6KwDywJBcKyfCFgA&usqp=CAU", 
        description: "For the best home theater experience", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "80in  8k TV", 
        price: 6000, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2BoeoAfYZurCwcsaia_pMxF0upwJ7hxAAoA&usqp=CAU", 
        description: "Extremely AMAZING TV, very vibrant and high quality", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Record Player", 
        price: 125, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.jwSxezFsABXC4QxgQ3XFlwAAAA%26pid%3DApi&f=1", 
        description: "Its a CLASSIC how could you not", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Mighty Ducks Jersey", 
        price: 90, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.g0Wpvs5dgAsV-oPbl0W_swHaHU%26pid%3DApi&f=1", 
        description: "Everyone's favorite character GOLDBERG", 
        category: "Clothing", 
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Vintage Boyfriend Jeans", 
        price: 15, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.wWFO1ngeKMKTNAcLICSjpgHaHa%26pid%3DApi&f=1", 
        description: "Both pair of jeans included purse and shoes not included", 
        category: "Clothing", 
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Computer Desk", 
        price: 130, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.JJH22FLbRz1keqjBSOwT2AHaHa%26pid%3DApi&f=1", 
        description: "Really good for at home work or taking a software engineer immersive course", 
        category: "Furniture",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Ipod touch", 
        price: 30, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.UifRXhpERr0p20VStPCkrwHaHa%26pid%3DApi&f=1", 
        description: "All the good tunes and vibes included", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "NASA Dad Hat", 
        price: 12, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.ZaJui0OdnHWQbbvbNuDByQHaHa%26pid%3DApi&f=1", 
        description: "Good Quality", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Ultimate Villian Jersey", 
        price: 90, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.zUeXY9DTlZo37oxnkhfnGQHaFj%26pid%3DApi&f=1", 
        description: "Love him or Hate him", 
        category: "Clothing",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Ultimate Villian Jersey part 2", 
        price: 75, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.F2DqVo1R8Et2XJgIYygSGgHaFf%26pid%3DApi&f=1", 
        description: "Love him or Hate him", 
        category: "Clothing",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "HP 15-inch Gaming Laptop", 
        price: 3300, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.fJWbsuHyqiACVxbj9jTfqAHaFX%26pid%3DApi&f=1", 
        description: "High Quality Gaming", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "In Home Bar", 
        price: 75, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.d6oVXTr7Jv-ow0VjCH6DugHaFt%26pid%3DApi&f=1", 
        description: "Extremely heavy", 
        category: "Furniture",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Gaming Chair", 
        price: 249, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.ghrHhveUCPZYwSBrQlRRIwHaHa%26pid%3DApi&f=1", 
        description: "Enjoy the experience", 
        category: "Furniture", 
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "PS5", 
        price: 750, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.rl6tC5Ng5yNVrUzavaubawHaD5%26pid%3DApi&f=1", 
        description: "Still in box", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Irobot Roomba", 
        price: 200, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.oMzC8EHhZHJ9Uxs0R6q5PQHaHa%26pid%3DApi&f=1", 
        description: "Slightly used but still in great shape and performs well", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Antique Boombox", 
        price: 475, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.tyk9pYXuUXZ5Kf5XLkvuiwHaE7%26pid%3DApi&f=1", 
        description: "Fully Functional", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "Custom Timberland", 
        price: 75, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.Ywkozr0wFvOEAoM9__s9UQHaHC%26pid%3DApi&f=1", 
        description: "I MAKE CUSTOM SHOES FOLLOW ME ON IG @chrisDollars$$", 
        category: "Clothing",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "SEGA GENESIS", 
        price: 45, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.zKkzHgcVDQwVInfzy8UM9gHaE9%26pid%3DApi&f=1", 
        description: "OLD BUT NEW", 
        category: "Electronics", 
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "SIGNED KOBE JERSEY", 
        price: 25000, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.mYH-AKTHIIPEc33xkYOMGQHaIL%26pid%3DApi&f=1", 
        description: "RIP KOBE AND GIGI", 
        category: "Clothing",
        sellerUser: 123, 
        sold: false, 
    }, 
];