module.exports = [
    {
        name: "Couch", 
        price: 100, 
        image: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.home-dzine.co.za%2F2016%2Fjan%2F189.jpg&f=1&nofb=1", 
        description: "This is a great couch.", 
        category: "Furniture",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "TV Stand", 
        price: 75, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.ZPVnC2W9OXTPZtEpv8yrbgAAAA%26pid%3DApi&f=1", 
        description: "As good as new tv is not including", 
        category: "Furniture",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "X-MEN Acrade Game", 
        price: 1700, 
        image: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F1.bp.blogspot.com%2F_j47CXrjYTRg%2FTR6vI599jfI%2FAAAAAAAAAIg%2FWRY5SGQ8GPM%2Fs1600%2Fxmenarcade.jpg&f=1&nofb=1", 
        description: "Fully Operational and Awesome", 
        catergory: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "HD Projector", 
        price: 699, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIVmJD50Ao_aPXb_Dpvg6KwDywJBcKyfCFgA&usqp=CAU", 
        description: "For the best home theater experience", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
    {
        name: "80in  8k TV", 
        price: 6000, 
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2BoeoAfYZurCwcsaia_pMxF0upwJ7hxAAoA&usqp=CAU", 
        description: "Extremely AMAZING TV, very vibrant and high quality", 
        category: "Electronics",
        sellerUser: 123, 
        sold: false, 
    }, 
];