module.exports = [
    {
        rating: 4, 
        title: "Good Review", 
        content: "This seller was honest and good to buy from.", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 3, 
        title: "ehhhhhh", 
        content: "Its doing the job so i wont complain but complaints could be made.", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 5, 
        title: "Highly Recommended", 
        content: "Transaction was smooth and the product works amazingly", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 4, 
        title: "Lifesaver", 
        content: "Will definitely buy from them again.", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 1, 
        title: "Why even sell this", 
        content: "Product was completely useless", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 5, 
        title: "Mind Blown", 
        content: "OMG I was scared these wouldnt fit but they fit perfectly.", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 3, 
        title: "SO-SO", 
        content: "I was expecting more but it is as advertised so i cant complain", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 5, 
        title: "PERFECT", 
        content: "Absoulutely love it I'll 100% stand buy this seller they hit the nail on the head", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 4, 
        title: "I would do it again", 
        content: "A little banged up but exactly what I needed.", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 1, 
        title: "ARE U SERIOUS", 
        content: "This product is a fraud completely not as described.", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
    {
        rating: 4, 
        title: "Ecstatic", 
        content: "I know you see this fit on me.", 
        reviewedSellerUser: 123, 
        reviewingBuyerUser: 123, 
    }, 
];