module.exports = [
    {
        userName: "JaneDoe123", 
        firstName: "Jane", 
        lastName: "Doe", 
        location: "New York", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.QVd2TToiairiy_E28sOYhQAAAA%26pid%3DApi&f=1", 
        averageRating: 3.5, 
        seed_id: 1, 
    }, 
    {
        userName: "AliceWalker123", 
        firstName: "Alice", 
        lastName: "Walker", 
        location: "New York", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.0W5W4xqVXEn_q25EhSdm5QHaJQ%26pid%3DApi&f=1", 
        averageRating: 2.1, 
        seed_id: 2, 
    }, 
    {
        userName: "chrisDollars$$", 
        firstName: "Christopher", 
        lastName: "Augustine", 
        location: "Boston", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.uni-regensburg.de%2FFakultaeten%2Fphil_Fak_II%2FPsychologie%2FPsy_II%2Fbeautycheck%2Fenglish%2Fprototypen%2Fm_sexy_gr.jpg&f=1&nofb=1", 
        averageRating: 4.4, 
        seed_id: 3, 
    },
    {
        userName: "MaryWisdom21", 
        firstName: "Marissa", 
        lastName: "Wisdom", 
        location: "New York", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.CUnT6hA2NQLYYVHKLsyEiwAAAA%26pid%3DApi&f=1", 
        averageRating: 3.0, 
        seed_id: 4, 
    },
    {
        userName: "defaultUser15", 
        firstName: "Jenny", 
        lastName: "Tua", 
        location: "Boston", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.QVd2TToiairiy_E28sOYhQAAAA%26pid%3DApi&f=1", 
        averageRating: 4.9, 
        seed_id: 5, 
    }, 
    {
        userName: "pjmasks2015", 
        firstName: "Amya", 
        lastName: "Greg", 
        location: "Boston", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.dbmcpa.com%2Fwp-content%2Fuploads%2F2017%2F07%2Fgeneric-female-headshot.png&f=1&nofb=1", 
        averageRating: 4.6, 
        seed_id: 6, 
    }, 
    {
        userName: "onlySpidey", 
        firstName: "Tobi", 
        lastName: "Maguire", 
        location: "New York", 
        profileImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3QVJaVms5OJ5rU1qMAV6OIBkYqMtzPpN0Vg&usqp=CAU", 
        averageRating: 4.9, 
        seed_id: 7, 
    }, 
    {
        userName: "callMeCap", 
        firstName: "Carol", 
        lastName: "Danvers", 
        location: "Boston", 
        profileImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSN-2K0GXbH6WoQIUIzhgly_5TAsHsaN9Z3Vg&usqp=CAU", 
        averageRating: 4.8, 
        seed_id: 8, 
    }, 
    {
        userName: "bluedevils", 
        firstName: "Greyson", 
        lastName: "Redick", 
        location: "Boston", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.sportscasting.com%2Fwp-content%2Fuploads%2F2020%2F09%2FGrayson-Allen-Duke.jpg&f=1&nofb=1", 
        averageRating: 4.6, 
        seed_id: 9, 
    }, 
    {
        userName: "theMightyDuck", 
        firstName: "Greg", 
        lastName: "Goldberg", 
        location: "Boston", 
        profileImage: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.the-sun.com%2Fwp-content%2Fuploads%2Fsites%2F6%2F2020%2F09%2FNINTCHDBPICT000455136836.jpg&f=1&nofb=1", 
        averageRating: 4.7, 
        seed_id: 10, 
    }, 
];